# Generated by Django 3.0 on 2021-11-20 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
