# Generated by Django 3.0 on 2021-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
